### ISSUE TITLE
Dynamic map marker contents

### ISSUE THREAD

**Issue by frietboer** [gsarig/ootb-openstreetmap#49]
Is there a way of having the marker popup content in a dynamic map, be filled by the corresponding post title, excerpt and permalink?

**Comment by gsarig** [comment]
Hi @frietboer Are you referring to the new feature that draws the info from the new "Location" custom field, as described [here](https://github.com/gsarig/ootb-openstreetmap/releases/tag/2.8.0)?

**Comment by frietboer** [comment]
No I hadn't seen that new feature yet! I was referring to the map that "syncs" locations from posts, or with the [ootb_query] shortcode. But I can image that this could be the same for the new feature.

**Comment by gsarig** [comment]
This request would make more sense for the new feature than the standard query. The reason is that the standard query gathers the locations from the blocks, and each post can have multiple blocks and each block, in turn, can have multiple markers, so it wouldn't make sense to override all the markers' values with the post's data. 

The new "Location" feature, though, only allows a single marker, and is tied to the post. So, I could perhaps look into extending its functionality to add some hook with which you could override the default output.

**Comment by frietboer** [comment]
Yes that would make more sense. 
A hook would be ideal. If one could hook into the popup content as well as the marker icon, I would imagine that this would greatly enhance the possibilities of this plugin.

**Comment by gsarig** [comment]
Hi @frietboer Just letting you know that this has been implemented with version v.2.8.2. More specifically, two hooks have been introduced, allowing you to fully modify the content of the modal, as well as the marker's icon. You can read more details, along with examples, in the [Release Notes](https://github.com/gsarig/ootb-openstreetmap/releases/tag/v.2.8.2). 

I'm closing this ticket as done!
